### ISSUE TITLE
any file extension chat

### ISSUE THREAD

**Issue by huzaifa-python** [supabase-community/chatgpt-your-files#16]
# Feature request

any file extension chat

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

**Comment by gregnr** [comment]
@huzaifa-python thanks for the suggestion. This tutorial was designed to give you the foundation for the chat-with-your-files concept (via markdown files) with the idea that you can extend it to support other file types that you're interested in.

We're looking to see what we can do to support some other common files types (PDFs, DOCX, etc) for more general use-cases at Supabase, but for this repo I'd suggest we keep the implementation simple for now.
