### ISSUE TITLE
npx supabase functions deploy

### ISSUE THREAD

**Issue by jhancock** [supabase-community/chatgpt-your-files#20]
# Improve documentation

## Link 

(https://github.com/supabase-community/chatgpt-your-files/blob/main/README.md)

## Describe the problem

jon@local~/c/p/chatgpt-your-files $ npx supabase functions deploy
Bundling chat
failed to start docker container: Error response from daemon: failed to create task for container: failed to initialize logging driver: dial tcp 127.0.0.1:54328: connect: connection refused

## Describe the improvement

This part is killing me.  I am doing the tutorial fully in cloud and get stuck on deploying functions.  It seems like it is trying to use local docker.

**Comment by gregnr** [comment]
Hey @jhancock - your error sounds familiar. By chance, can you try setting `enabled = false` to the [`analytics` section](https://github.com/supabase-community/chatgpt-your-files/blob/c90398bd8424762cd718b8573ebd027825fd8983/supabase/config.toml#L130) of `config.toml` and let me know if that fixes this?

**Comment by jhancock** [comment]
that works!  thanks
