### ISSUE TITLE
Supabase Installation Issues in WSL2

### ISSUE THREAD

**Issue by iwo9** [supabase-community/chatgpt-your-files#22]
# Bug report
Supabase not installing via npm in WSL2

## Describe the bug
Trying supabase installation but fails every time.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Install WSL2
Run sudo apt-get install -y nodejs
Run npm i -D supabase@1.102.0

## System information
- OS: Windows 11
- Browser
- Version of supabase-js: 
- Version of Node.js: v12.22.9

## Additional context
maryam@DESKTOP-KP4KII1:~/chatgpt-your-files$ npm i -D supabase@1.102.0
npm ERR! code 1
npm ERR! path \\wsl.localhost\Ubuntu\home\maryam\chatgpt-your-files\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! '\\wsl.localhost\Ubuntu\home\maryam\chatgpt-your-files\node_modules\sharp'
npm ERR! CMD.EXE was started with the above path as the current directory.
npm ERR! UNC paths are not supported.  Defaulting to Windows directory.
npm ERR! node:internal/modules/cjs/loader:1080
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\Windows\install\libvips'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:922:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR!
npm ERR! Node.js v18.17.1
npm ERR! node:internal/modules/cjs/loader:1080
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\Windows\install\can-compile'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:922:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR!
npm ERR! Node.js v18.17.1

npm ERR! A complete log of this run can be found in: C:\Users\marya\AppData\Local\npm-cache\_logs\2024-03-13T10_33_11_606Z-debug-0.log
maryam@DESKTOP-KP4KII1:~/chatgpt-your-files$

**Comment by gregnr** [comment]
Hey @iwo9! Your system may be trying to use a Windows version of node/npm from within WSL2 instead of a Linux one. Would you mind running:
```shell
which node
```
and
```shell
which npm
```
from within WSL2 and report back the paths for each?

If they're pointing to a location mounted in windows (eg. `/mnt/c/...`), you can try [installing node from within Linux](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-nvm-nodejs-and-npm) instead.

**Comment by iwo9** [comment]
Yup that solved it, thanks!
