### ISSUE TITLE
Error when trying to embed a md file

### ISSUE THREAD

**Issue by enthusiastic2003** [supabase-community/chatgpt-your-files#23]
# Bug report
## Describe the bug
Currently trying to follow step 3. after executing npx supabase functions serve , and i upload the files on the website, i can see the files in the document section of the table editor but i all embedding vecotrs are NULL. 

This is the error I am receiving:
`Segmentation fault (core dumped)
2024/03/24 03:41:56 Sent Header: Host [api.moby.localhost]
2024/03/24 03:41:56 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/03/24 03:41:56 Send Done
2024/03/24 03:41:57 Recv First Byte
error running container: exit 139`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `git checkout step-4` & `npm supabase start`
3. `npm run dev` & `npx supabase functions serve`
4. upload file to localhost:3000.
5. In the terminal where you ran `npx supabase functions serve`, this error would be shown

## Expected behavior

The file should have been uploaded and embedding vectors should have been shown in the  table editor. 

## Screenshots

![Screenshot_20240324_035754](https://github.com/supabase-community/chatgpt-your-files/assets/40400917/2a88e6dd-233e-451a-87dc-0da93ab77652)

## System information

- OS: Ubuntu, 23.10
- Browser (if applies) Firfox
- Version of supabase-js: Latest Version
- Version of Node.js: 13.5.4

**Comment by gregnr** [comment]
Hey @enthusiastic2003, thanks for reporting and sorry for the delay. Could you please confirm which version of the edge runtime you are running? You can check by running:
```shell
npx supabase services
```
