### ISSUE TITLE
Error uploading to storage.

### ISSUE THREAD

**Issue by isley-griffith** [supabase-community/chatgpt-your-files#34]
# Bug report

## Describe the bug

Hello,

After connecting it up to a Supabase project, I am getting the following error when uploading through the application or through the Supabase dashboard:

`Failed to upload roman-empire-1.md: insert into "objects" ("bucket_id", "metadata", "name", "owner", "owner_id", "version") values ($1, DEFAULT, $2, DEFAULT, DEFAULT, $3) - null value in column "url" of relation "http_request_queue" violates not-null constraint`

I am doing the cloud Supabase version.

## To Reproduce

1. Clone the project (main branch)
2. Create a new Supabase project
3. Add the appropriate variables to your .env
4. Run `npm i`
5. Run `supabase link --project-ref=<your-ref>`
6. Run `npx supabase db push`
7. Run `npm run dev` and try to upload a .md file.
8. Alternatively, try to upload a .md file directly to the bucket via the Supabase dashboard.

## Expected behavior

To be able to upload a .md file.

## Screenshots

<img width="404" alt="image" src="https://github.com/supabase-community/chatgpt-your-files/assets/48958109/335d3c79-6d02-45f0-a54f-703aed026083">

<img width="1728" alt="image" src="https://github.com/supabase-community/chatgpt-your-files/assets/48958109/a4cb1761-8890-4164-92ad-ca9397379fb1">

## System information

- OS: macOS, Macbook Pro M1 Max

- Version of supabase-js: latest
- Version of Node.js: 18.17.1

**Comment by Nishanth-Gobi** [comment]
@isley-griffith I am facing the same issue, can you share how you've fixed it?

**Comment by clementpeleman** [comment]
What did you do to fix this?

**Comment by isley-griffith** [comment]
@clementpeleman Make sure you set the secret in the vault.

After replacing with your project-id, run the following:

```
select vault.create_secret(
  'https://<your-project-id>.supabase.co',
  'supabase_url'
);
```

**Comment by clementpeleman** [comment]
Great, thanks!
I thought this file did run automatically..

**Comment by isley-griffith** [comment]
@clementpeleman unfortunately it requires your unique project-id. Quite the headache, this one.

**Comment by isley-griffith** [comment]
@clementpeleman It is to call the proper edge function.

In this function:

```
create function private.handle_storage_update()
returns trigger 
language plpgsql
as $$
declare
  document_id bigint;
  result int;
begin
  insert into documents (name, storage_object_id, created_by)
    values (new.path_tokens[2], new.id, new.owner)
    returning id into document_id;

  select
    net.http_post(
      url := supabase_url() || '/functions/v1/process',            <==============
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', current_setting('request.headers')::json->>'authorization'
      ),
      body := jsonb_build_object(
        'document_id', document_id
      )
    )
  into result;

  return null;
end;
$$;
```

The proper edge function, "/functions/v1/process" is appended to the supabase_url, which is what you provide to the vault.
