### ISSUE TITLE
Model output does not come to the Chat UI after receiving a response from the request

### ISSUE THREAD

**Issue by onurhan1337** [supabase-community/chatgpt-your-files#38]
# Bug report

I developed a similar website by following all the steps. Everything works fine, but there is only one problem that I can't solve, I write a prompt to chat and send it, then it works fine and I get output (can be viewed via Google devtools) but the output generated in the chat UI is not seen. 

I didn't add an extra piece of code or do anything different, could it be due to different versions of the packages used? I'm not getting any error.

## Describe the bug

Model output does not come to the Chat UI after receiving a response from the request

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Write a text to chat
2. Press f12 or right click and inspect the page
3. Go to network tab
4. See the request and click related request
5. See correct response
6. Can't see this response in the chat UI without any error

## Expected behavior

Render the coming response to Chat UI.

## Screenshots

![image](https://github.com/supabase-community/chatgpt-your-files/assets/60575283/21ac22aa-9a18-4e42-bf21-ff1c72fd67bd)
![image](https://github.com/supabase-community/chatgpt-your-files/assets/60575283/96f8ed8c-3640-405d-a01f-805c22e0efd5)

## System information

- OS: Windows
- Browser: Chrome
- Version of supabase-js: v2.43.4
- Version of Node.js: v18.18.0

**Comment by aattsai** [comment]
@onurhan1337 I had the same issue with AI SDK 3.0^ where the response isn't displayed. Like you, I downgraded the package to 2.2.14 and it worked as expected. Have you ever figured out what changed?

**Comment by onurhan1337** [comment]
@aattsai, I'm sorry to hear that you're having a similar problem. I've actually looked at the changes, but I still can't figure out what triggers this error, so I'm "forced" to stick with version 2.2.14.

The packages are updated really fast, and when I tried to write the project myself step by step I encountered many new bugs.

**Comment by sgruhier** [comment]
Same I stayed on 2.2.14. That's an big problem with vercel/ai package.
